### ISSUE TITLE
function range2cidrlist returns error

### ISSUE THREAD

**Issue by Foxwoud** [jmaslak/Net-Netmask#5]
Hello,
when i try to use the function range2cidrlist with a start ip and end ip in parameters, it returns an error. It seems that the parameters passed to the function are including an Net::Netmask object which is not declared in the function.
If in Netmask.pm line 775 i add $this in parameter, it works.

The error :
`Use of uninitialized value $start in numeric gt (>) at lib/perl5/Net/Netmask.pm line 787, <$file> line 6660.`
`Use of uninitialized value $start in numeric ge (>=) at lib/perl5/Net/Netmask.pm line 799, <$file> line 6660.`
 `at lib/perl5/Net/Netmask.pm line 761, <$file> line 6660.`
  `      Net::Netmask::imaxblock(undef, 32, "IPv4") called at lib/perl5/Net/Netmask.pm line 800`
   `     Net::Netmask::irange2cidrlist(undef, 2653851648, "IPv4") called at lib/perl5/Net/Netmask.pm line 789`
    `    Net::Netmask::range2cidrlist("Net::Netmask", "158.46.144.0", "158.46.145.12") called at scripts/ioc-filter.pl line 419`

My code : 
`if ($line =~ /^range\,(\d+\.\d+\.\d+\.\d+)\-(\d+\.\d+\.\d+\.\d+)$/) {`
 `           my $start = $1 ;`
 `           my $end   = $2 ;`
 `           my @objects = Net::Netmask->range2cidrlist($start,$end);`
`}`

**Comment by jmaslak** [comment]
Hello,

The `range2cidrlist()` routine is not a class method, so it should be called as `range2cidr($start, $end)` (without the leading `Net::Netmask->`).  Whenever you use the arrow, it passes the object (in this case, just the Net::Netmask class itself) as the first parameter to the sub, which is why the error occurred.

I.E. your code should look like:
```
if ($line =~ /^range\,(\d+\.\d+\.\d+\.\d+)\-(\d+\.\d+\.\d+\.\d+)$/) {
    my $start = $1 ;
    my $end = $2 ;
    my @objects = range2cidrlist($start,$end);
}
```

Please let me know if this helps you out, so I can close the bug or investigate it further.

**Comment by Foxwoud** [comment]
Oh, i see. Sorry for the misunderstanding and thank you for the explanations =)
